name: Setup
description: Setup Node.js, pnpm, and dependencies

runs:
  using: composite
  steps:
    - uses: Kesin11/actions-timeline@v2
    - uses: pnpm/action-setup@v4
    - uses: actions/setup-node@v4
      with:
        cache: 'pnpm'
        registry-url: 'https://registry.npmjs.org'
        node-version-file: 'package.json'
    - shell: bash
      run: pnpm --frozen-lockfile install
