name: Release

on:
  push:
    branches:
      - main
env:
  FORCE_COLOR: true

jobs:
  changelog:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: pnpm check
      - run: pnpm build
      - run: npm config set '//registry.npmjs.org/:_authToken' '$NPM_TOKEN'
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          publish: pnpm release
          commit: 'chore: release'
          title: '[ci] release'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
