name: Snapshot

on:
  - push
  - pull_request

jobs:
  publish-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - run: pnpm build
      - run: pkg-pr-new publish --pnpm --compact
